### ISSUE TITLE
hello,I have questions for LSENet\test.py and usage time of the full run program

### ISSUE THREAD

**Issue by 3434446820** [lliusha1155/LSENet#2]
(1)model.load_weights(log_dir + '71.75.h5')
This sentence means to perform a read of 71.75.h5 under the log_dir path in order to use the weight data for prediction in the next step.When run, an error is reported showing that the weight data being read does not match the network.
(2) I read the code article in detail, and I have to say, you're really great to make the code and dataset available online!In the article, you mentioned running in an NVIDIA RTX 3080 graphic processing unit (GPU) with 10 10-GB memory environment. I would like to know how long it takes to run LSENet/train.py (for China offshore data) and LSENet/train_Mexico.py (for Gulf of Mexico data) respectively.

I would be grateful if you could reply to me sometime!❤

**Comment by lliusha1155** [comment]
(1) We are very sorry that due to personal negligence, our latest model was not uploaded. The code in the file Model.py has been corrected, and it should work normally.
In addition, the file 71.75.h5 is larger than 100MB, which has exceeded the file size limit of GitHub. We uploaded it using git LFS. The original file cannot be obtained by direct cloning without git LFS (software for managing git large files). We suggest you download it here (as shown in the attached figure).
 
(2) The training time under the two data sets is about 2-4 hours
![11](https://user-images.githubusercontent.com/55483751/178182622-1523497b-10a6-4186-a7fa-e3fb09c5d8bb.png)

**Comment by 3434446820** [comment]
Hello, when I reproduce the binary classification problem (only background and front), I set the number of categories to 2, and the initial epoch0 runs 80epoch to get the result front accuracy fluctuates around 50%, how to get the accuracy of about 70% in the paper? If it is not convenient to communicate on GitHub, you can contact my email niurui19981120@outlook.com

**Comment by lliusha1155** [comment]
The operation is very simple. We still use multi classification for training, but set the category whose category number is greater than 1 in the prediction result to 1, so as to get the result of the second classification。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月23日(星期天) 晚上7:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lliusha1155/LSENet] hello,I have questions for LSENet\test.py and usage time of the full run program (Issue #2)





 
Hello, when I reproduce the binary classification problem (only background and front), I set the number of categories to 2, and the initial epoch0 runs 80epoch to get the result front accuracy fluctuates around 50%, how to get the accuracy of about 70% in the paper? If it is not convenient to communicate on GitHub, you can contact my email ***@***.***

**Comment by 3434446820** [comment]
Thank you for your reply, but after I use this method, after the epoch_max is set to 120, the maximum mIoU is 80.2, my computer configuration is low, is this result related to the computer configuration? I would like to make sure that the results in the paper have set the initial weight, and when epoch_max can I get satisfactory results?
